# Generated by Django 4.2.16 on 2024-10-26 17:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile_image2',
            field=cloudinary.models.CloudinaryField(default='placeholder2', max_length=255, verbose_name='image2'),
        ),
    ]
