# Generated by Django 4.2.16 on 2024-10-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_profile_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboraterequest',
            name='luxury_category',
            field=models.CharField(default='luxury_category', max_length=100),
            preserve_default=False,
        ),
    ]
